const maleFirstNames = ['Erik', 'Lars', 'Karl', 'Anders', 'Johan', 'Per', 'Carl', 'Nils', 'Mikael', 'Jan', 'Hans', 'Peter', 'Olof', 'Lennart', 'Gunnar', 'Sven', 'Fredrik', 'Daniel', 'Bengt', 'Bo', 'Alexander', 'Gustav', 'Göran', 'Åke', 'Magnus', 'Andreas', 'Martin', 'Stefan', 'John', 'Mats', 'Leif', 'Ulf', 'Thomas', 'Björn', 'Henrik', 'Jonas', 'Axel', 'Christer', 'Robert', 'Bertil', 'David', 'Emil', 'Arne', 'Ingemar', 'Håkan', 'Kjell', 'Mattias', 'Stig', 'Rolf', 'William', 'Oskar', 'Michael', 'Patrik', 'Tommy', 'Roland', 'Simon', 'Joakim', 'Christian', 'Oscar', 'Anton', 'Sebastian', 'Marcus', 'Roger', 'Gustaf', 'Ingvar', 'Eric', 'Tomas', 'Viktor', 'Olov', 'Hugo', 'Johannes', 'Tobias', 'Elias', 'Adam', 'Niklas', 'Kent', 'Emanuel', 'Ove', 'Robin', 'Jörgen', 'Filip', 'Ali', 'Rune', 'Kenneth', 'Gösta', 'Wilhelm', 'Arvid', 'Linus', 'Albin', 'Jonathan', 'Oliver', 'Olle', 'Dan', 'Rickard', 'Sten', 'Kurt', 'Alf', 'Henry', 'Claes', 'Vilhelm', 'Samuel', 'Jesper', 'Joel', 'Max', 'Torbjörn', 'Victor', 'Ola', 'Harry', 'Gabriel', 'Börje', 'Christoffer', 'Ivar', 'Leo', 'Allan', 'Rasmus', 'Markus', 'Mohamed', 'Paul', 'Edvin', 'Jens', 'Georg', 'Philip', 'Jimmy', 'Richard', 'Folke', 'Krister', 'Ludvig', 'Mohammad', 'Ahmed', 'Dennis', 'Pär', 'Alfred', 'Inge', 'Bror', 'Pontus', 'Bernt', 'Isak', 'Liam', 'Benjamin', 'Lucas', 'Birger', 'Evert', 'Sören', 'Kristian', 'Ragnar', 'Mohammed', 'Jakob', 'Vincent', 'Tony', 'Felix', 'Einar', 'Kevin', 'Mathias', 'Tore', 'Jacob', 'Conny', 'Lukas', 'Harald', 'Knut', 'Tage', 'Torsten', 'Niclas', 'Yngve', 'Kristoffer', 'André', 'Klas', 'Adrian', 'Hampus', 'Otto', 'Sture', 'Ahmad', 'Sixten', 'Valdemar', 'Sune', 'Kim', 'Ivan', 'Staffan', 'Johnny', 'Charlie', 'Noah', 'Ronny', 'Josef', 'August', 'Urban', 'Albert', 'Morgan', 'Tim', 'Ernst', 'Valter', 'Benny', 'Göte', 'Frank', 'Jonny', 'Theodor', 'Petter', 'Sigvard', 'Nicklas', 'Elliot', 'Rikard', 'Ibrahim', 'Love'];

const femaleFirstNames = ['Maria', 'Anna', 'Margareta', 'Elisabeth', 'Eva', 'Kristina', 'Birgitta', 'Karin', 'Marie', 'Elisabet', 'Ingrid', 'Christina', 'Sofia', 'Linnéa', 'Lena', 'Kerstin', 'Helena', 'Marianne', 'Emma', 'Linnea', 'Johanna', 'Inger', 'Sara', 'Cecilia', 'Elin', 'Anita', 'Louise', 'Ida', 'Linda', 'Gunilla', 'Susanne', 'Hanna', 'Ulla', 'Malin', 'Viola', 'Katarina', 'Jenny', 'Carina', 'Elsa', 'Monica', 'Astrid', 'Alice', 'Ulrika', 'Julia', 'Irene', 'Annika', 'Viktoria', 'Barbro', 'Amanda', 'Åsa', 'Matilda', 'Therese', 'Camilla', 'Lovisa', 'Ann', 'Yvonne', 'Siv', 'Caroline', 'Agneta', 'Britt', 'Lisa', 'Charlotte', 'Sandra', 'Frida', 'Sofie', 'Ingegerd', 'Anette', 'Gun', 'Ebba', 'Emelie', 'Emilia', 'Margaretha', 'Ellen', 'Alexandra', 'Victoria', 'Berit', 'Erika', 'Charlotta', 'Maja', 'Jessica', 'Olivia', 'Anneli', 'Inga', 'Agnes', 'Märta', 'Pia', 'Madeleine', 'Ella', 'Felicia', 'Mona', 'Ingeborg', 'Josefin', 'Karolina', 'Gunnel', 'Signe', 'Sonja', 'Lina', 'Magdalena', 'Helen', 'Stina', 'Birgit', 'Monika', 'Ingela', 'Alva', 'Josefine', 'Evelina', 'Gerd', 'Anne', 'Moa', 'Pernilla', 'Rut', 'Elvira', 'Lisbeth', 'Maj', 'Saga', 'Marita', 'Alma', 'Jeanette', 'Solveig', 'Nina', 'Ingegärd', 'Veronica', 'Carolina', 'Isabelle', 'Klara', 'Isabella', 'Helene', 'Rebecca', 'Kristin', 'Britt-Marie', 'Linn', 'Mari', 'Petra', 'Ester', 'Vera', 'Rebecka', 'Lilian', 'Wilma', 'Lilly', 'Ruth', 'Sigrid', 'Alicia', 'Elise', 'Gunvor', 'Gudrun', 'Nathalie', 'Mikaela', 'Martina', 'Susanna', 'Margit', 'Ellinor', 'Angelica', 'Christine', 'Annie', 'Jennifer', 'Iris', 'Laila', 'Clara', 'Britta', 'Gabriella', 'Greta', 'Annelie', 'Kajsa', 'Svea', 'Eleonora', 'Carin', 'Jennie', 'Maud', 'Iréne', 'Ewa', 'Filippa', 'Sanna', 'Selma', 'Ann-Charlotte', 'Annette', 'Marina', 'Fanny', 'Elina', 'Ann-Marie', 'Ylva', 'My', 'Marie-Louise', 'Lillemor', 'Eivor', 'Cornelia', 'Stella', 'Mary', 'Andrea', 'Beatrice', 'Inga-Lill', 'Catharina', 'Siri', 'Maj-Britt', 'Therése', 'Aina', 'Ann-Christin', 'Molly', 'Catarina', 'Nora', 'Mathilda', 'Rose-Marie'];

const firstNames = [ ...maleFirstNames, ...femaleFirstNames ];

const lastNames = ['Andersson', 'Johansson', 'Karlsson', 'Nilsson', 'Eriksson', 'Larsson', 'Olsson', 'Persson', 'Svensson', 'Gustafsson', 'Pettersson', 'Jonsson', 'Jansson', 'Hansson', 'Bengtsson', 'Carlsson', 'Jönsson', 'Lindberg', 'Petersson', 'Magnusson', 'Lindström', 'Gustavsson', 'Olofsson', 'Lindgren', 'Axelsson', 'Bergström', 'Lundberg', 'Lundgren', 'Berg', 'Jakobsson', 'Berglund', 'Sandberg', 'Fredriksson', 'Mattsson', 'Sjöberg', 'Forsberg', 'Ali', 'Henriksson', 'Lind', 'Lindqvist', 'Engström', 'Eklund', 'Lundin', 'Danielsson', 'Håkansson', 'Holm', 'Bergman', 'Gunnarsson', 'Samuelsson', 'Nyström', 'Wallin', 'Lundqvist', 'Björk', 'Fransson', 'Holmberg', 'Johnsson', 'Nyberg', 'Söderberg', 'Arvidsson', 'Isaksson', 'Nordström', 'Ahmed', 'Mårtensson', 'Lundström', 'Björklund', 'Berggren', 'Eliasson', 'Sandström', 'Nordin', 'Ström', 'Åberg', 'Ekström', 'Hermansson', 'Mohamed', 'Holmgren', 'Hedlund', 'Sundberg', 'Sjögren', 'Dahlberg', 'Öberg', 'Hellström', 'Martinsson', 'Blom', 'Strömberg', 'Ek', 'Falk', 'Månsson', 'Abrahamsson', 'Blomqvist', 'Lindholm', 'Norberg', 'Åkesson', 'Sundström', 'Löfgren', 'Dahl', 'Åström', 'Jonasson', 'Hassan', 'Söderström', 'Jensen', 'Nyman', 'Ivarsson', 'Andreasson', 'Bergqvist', 'Ibrahim', 'Lund', 'Hansen', 'Palm', 'Göransson', 'Borg', 'Englund', 'Möller', 'Lindblom', 'Hallberg', 'Rosén', 'Sjöström', 'Ekman', 'Josefsson', 'Davidsson', 'Ottosson', 'Lindahl', 'Söderlund', 'Strand', 'Stenberg', 'Boström', 'Bäckström', 'Friberg', 'Hedberg', 'Skoglund', 'Holmström', 'Nygren', 'Adolfsson', 'Höglund', 'Strandberg', 'Börjesson', 'Björkman', 'Wikström', 'Nielsen', 'Lindén', 'Lilja', 'Erlandsson', 'Roos', 'Malm', 'Edlund', 'Claesson', 'Haglund', 'Johannesson', 'Moberg', 'Franzén', 'Aronsson', 'Melin', 'Norén', 'Viklund', 'Dahlgren', 'Dahlström', 'Östlund', 'Hussein', 'Blomberg', 'Holmqvist', 'Ericsson', 'Sundqvist', 'Vikström', 'Knutsson', 'Högberg', 'Alm', 'Öhman', 'Lindell', 'Pålsson', 'Nguyen', 'Sundin', 'Hedman', 'Nord', 'Olausson', 'Lundmark', 'Hedström', 'Sjödin', 'Oskarsson', 'Wiklund', 'Ståhl', 'Sköld', 'Molin', 'Abdi', 'Mohammed', 'Svärd', 'Lindblad', 'Hagström', 'Ljungberg', 'Linder', 'Boman', 'Ljung', 'Malmberg', 'Ekberg', 'Pedersen', 'Jacobsson', 'Lindh', 'Paulsson', 'Hellberg', 'Näslund', 'Ohlsson', 'Wahlström', 'Törnqvist'];

module.exports = {
  firstNames,
  lastNames
};
