const sentences = [
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  'Curabitur quis purus vitae velit dignissim varius eu eu leo.',
  'Pellentesque a felis egestas tellus mollis luctus in fringilla velit.',
  'Pellentesque ac magna fringilla, efficitur nulla vel, ullamcorper neque.',
  'Praesent luctus massa eget augue finibus semper.',
  'Sed venenatis quam non quam auctor, at convallis lorem scelerisque.',
  'Suspendisse semper odio ac tortor pretium, eu dignissim libero vestibulum.',
  'Aenean eleifend lacus pulvinar lacus elementum convallis.',
  'Nunc viverra lectus nec magna dapibus, vitae mattis erat ullamcorper.',
  'Curabitur convallis sem eu orci euismod gravida.',
  'Nulla faucibus urna nec dui ornare porttitor.',
  'Proin maximus tortor quis massa mattis condimentum.',
  'Fusce mattis felis mollis sapien posuere, vitae condimentum purus venenatis.',
  'Fusce a eros eu urna malesuada euismod et et diam.',
  'Integer vel justo non metus accumsan tincidunt non eu enim.',
  'Suspendisse suscipit eros non dui malesuada, eget gravida eros sollicitudin.',
  'Donec nec massa venenatis, pretium enim placerat, dictum odio.',
  'Praesent eu odio non metus mollis gravida ultricies nec nisl.',
  'Integer lacinia ipsum at est varius, ut accumsan justo consectetur.',
  'Quisque tristique libero a turpis pretium condimentum.',
  'Suspendisse non libero rutrum nibh tincidunt fermentum.',
  'Integer ut mi eget tortor varius euismod.',
  'Mauris dapibus tortor id tincidunt porttitor.',
  'Etiam sit amet mauris et magna placerat interdum.',
  'Ut a ipsum ullamcorper, imperdiet est sed, cursus ante.',
  'Sed vulputate lectus in diam elementum viverra vel id leo.',
  'Maecenas quis ligula ut orci porttitor feugiat et non libero.',
  'Maecenas ut sem varius, egestas ante sed, dignissim purus.',
  'Aliquam tristique metus in nisl dignissim, a sollicitudin ipsum ultricies.',
  'Suspendisse vel enim vel mauris congue aliquam.',
  'Donec volutpat libero in rutrum fermentum.',
  'Fusce sodales urna a nunc tempus vestibulum.',
  'Donec aliquet tortor et magna lobortis, sed lobortis sem mattis.',
  'Nullam varius justo vel arcu auctor, non posuere dui aliquam.',
  'Etiam vulputate est vel ipsum hendrerit, sed pulvinar arcu fermentum.',
  'Duis sagittis mauris id sapien blandit ultricies.',
  'Nunc nec orci ut justo elementum luctus id vel est.',
  'Nunc eu nibh posuere, fermentum ex vel, interdum magna.',
  'Vestibulum sit amet est sit amet diam imperdiet commodo.',
  'Fusce eu tortor eget lectus tincidunt fermentum.',
  'Donec a odio et metus hendrerit mollis.',
  'Morbi auctor sem non ante blandit congue.',
  'Suspendisse sit amet felis viverra, malesuada arcu nec, ullamcorper enim.',
  'Nulla quis enim sollicitudin, efficitur mauris id, elementum ex.',
  'Nunc fermentum purus in pharetra commodo.',
  'In nec ipsum porta, ullamcorper nunc id, convallis urna.',
  'Proin eleifend odio vitae faucibus egestas.',
  'Maecenas sagittis sapien ac tellus vestibulum, sit amet ullamcorper nisl dignissim.',
  'Maecenas placerat dolor ac quam posuere tincidunt.',
  'Duis congue nibh at nisl tempor, in dictum nulla tristique.',
  'Donec id nisi venenatis purus bibendum maximus.',
  'Sed convallis purus quis turpis semper, id cursus nisi dignissim.',
  'Phasellus gravida lectus vel nisi rutrum consequat.',
  'Fusce convallis ante eu lectus suscipit, vitae pharetra leo fermentum.',
  'Praesent sit amet lectus efficitur, consequat sem a, ornare massa.',
  'Fusce blandit dolor et risus vulputate aliquam.',
  'Nullam eget orci sit amet mi viverra venenatis.',
  'Nam tristique arcu id nisi ultrices pharetra.',
  'Sed nec quam at est sollicitudin ullamcorper.',
  'Quisque eu justo ac diam blandit varius.',
  'Aenean fermentum dui mattis luctus mattis.',
  'Nullam ut augue condimentum felis dignissim consectetur non sit amet arcu.',
  'Fusce ac mauris sit amet tellus ultricies pellentesque at vel justo.',
  'Mauris id purus et metus dapibus tempor vitae eu ex.',
  'Sed at leo mollis, dignissim felis fringilla, dictum quam.',
  'Maecenas tincidunt erat ac aliquet tincidunt.',
  'Ut eleifend eros et lorem ornare congue.',
  'Sed hendrerit sapien et fringilla tincidunt.',
  'Nullam vitae elit ac lectus rutrum aliquam.',
  'Vestibulum sed massa non enim viverra tincidunt.',
  'Integer suscipit diam in sollicitudin placerat.',
  'Pellentesque non risus vel turpis pretium lobortis sit amet ut dui.',
  'Quisque posuere lacus ut orci scelerisque, ac vulputate lorem faucibus.',
  'Maecenas ac turpis laoreet, semper sem vitae, tristique tellus.',
  'Phasellus pharetra orci ut augue ornare maximus.',
  'Duis lacinia ante sit amet enim efficitur, et fermentum lectus suscipit.',
  'Praesent blandit lorem vitae nibh pharetra euismod.',
  'Phasellus et eros id lectus gravida auctor.',
  'Phasellus iaculis nisi a suscipit feugiat.',
  'Nunc vestibulum est at mi scelerisque, sed volutpat massa sodales.'
];

module.exports = sentences;
